// Catalogo prodotti organizzato per categoria e modello
// Ordinamento: per modello (più recente/premium prima), poi per variante colore/vista
// Immagini reali estratte da Apple Store (asset già presenti)

const IMG = 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b';

export const PRODUCT_CATALOG = [
  // === IPHONE 17 PRO ===
  {
    id: 1,
    name: 'iPhone 17 Pro — Arancione Cosmico',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/bb0ae7c20_IMG_1646.jpeg`,
    description: 'Lo smartphone più avanzato di sempre con finitura Arancione Cosmico. Chip A19 Pro, sistema fotocamera Pro con teleobiettivo 5x e display ProMotion da 6,3".',
  },
  {
    id: 2,
    name: 'iPhone 17 Pro — Deep Blue',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/bbc5ad376_IMG_1647.jpeg`,
    description: 'iPhone 17 Pro nella sofisticata finitura Deep Blue. Struttura in alluminio forgiato e vetro Ceramic Shield 2 di ultima generazione.',
  },
  {
    id: 3,
    name: 'iPhone 17 Pro — Argento',
    price: '€1.099',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/e0d184381_IMG_1648.webp`,
    description: 'Eleganza essenziale nella finitura Argento. Design ultra-sottile, prestazioni eccezionali e autonomia che dura tutto il giorno.',
  },
  {
    id: 9,
    name: 'iPhone 17 Pro — Vista Frontale',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/62e7a836b_IMG_1654.jpg`,
    description: 'Lo splendido display ProMotion da 120Hz dell\'iPhone 17 Pro. Luminosità fino a 2000 nit all\'aperto e True Tone per colori sempre perfetti.',
  },
  {
    id: 16,
    name: 'iPhone 17 Pro — Palette Colori',
    price: '€1.099',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/f661dd828_IMG_1661.jpeg`,
    description: 'Tre finiture esclusive per iPhone 17 Pro: Arancione Cosmico, Deep Blue e Argento. Scegli lo stile che ti rappresenta.',
  },
  {
    id: 12,
    name: 'iPhone 17 Pro — Macro Fotocamera',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/5819c7c2d_IMG_1657.jpeg`,
    description: 'Il sistema fotocamera Pro dell\'iPhone 17 Pro in dettaglio. Teleobiettivo 5x, grandangolo e ultra-grandangolo per foto da vero professionista.',
  },
  {
    id: 60,
    name: 'iPhone 17 Pro — Dettaglio Fotocamera',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/6594f9a7e_IMG_1663.jpeg`,
    description: 'Primo piano sul modulo fotocamera dell\'iPhone 17 Pro. Lenti smerigliate, sensore LiDAR e flash True Tone per risultati sorprendenti.',
  },
  {
    id: 61,
    name: 'iPhone 17 Pro — Sistema Tripla Fotocamera',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/db1a61bfe_IMG_1664.jpg`,
    description: 'Il sistema tripla fotocamera Pro: grandangolo, ultra-grandangolo e teleobiettivo 5x. Foto notturne, ritratti e macro di qualità professionale.',
  },
  {
    id: 66,
    name: 'iPhone 17 Pro — Macro Obiettivo',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/a53ee8668_IMG_1669.webp`,
    description: 'Macro estrema dell\'obiettivo fotocamera dell\'iPhone 17 Pro. Precisione millimetrica e qualità ottica superiore per catturare ogni dettaglio.',
  },
  {
    id: 15,
    name: 'iPhone 17 Pro — Dettagli Design',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/2d8934003_IMG_1660.jpeg`,
    description: 'I dettagli artigianali dell\'iPhone 17 Pro. Cornici ultra-sottili, pulsanti precisione e struttura in alluminio forgiato per un feel premium assoluto.',
  },
  {
    id: 14,
    name: 'iPhone 17 Pro — Lifestyle',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/f2bd4d78a_IMG_1659.jpeg`,
    description: 'iPhone 17 Pro nella vita di tutti i giorni. Prestazioni eccezionali per lavoro, creatività e intrattenimento senza limiti.',
  },
  {
    id: 17,
    name: 'iPhone 17 Pro — Render 3D',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/7d50b1a27_IMG_1662.jpeg`,
    description: 'Rendering 3D dell\'iPhone 17 Pro che mostra ogni dettaglio del design. Linee pulite, materiali premium e ingegneria di precisione.',
  },
  {
    id: 65,
    name: 'iPhone 17 Pro — Concept Arancione',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/928b2127d_IMG_1668.webp`,
    description: 'Concept design dell\'iPhone 17 Pro in Arancione Cosmico. Una visione futuristica che anticipa il design della prossima generazione.',
  },
  {
    id: 63,
    name: 'iPhone 17 Pro — Doppia Variante Arancione',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/5b70b72a5_IMG_1666.png`,
    description: 'Due esemplari di iPhone 17 Pro in Arancione Cosmico. Confronta il design anteriore e posteriore in un\'unica immagine d\'impatto.',
  },
  {
    id: 67,
    name: 'iPhone 17 Pro — Render 3D Arancione',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/b9530564b_IMG_1670.jpeg`,
    description: 'Render tridimensionale dell\'iPhone 17 Pro in Arancione Cosmico. Visualizza ogni angolazione del design più innovativo di Apple.',
  },

  // === IPHONE 17 PRO MAX ===
  {
    id: 7,
    name: 'iPhone 17 Pro Max — Arancione',
    price: '€1.199',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/65b3e0a90_IMG_1652.jpg`,
    description: 'Il modello Pro Max con il più grande display ever, batteria a lunga autonomia e fotocamera professionale. Finitura Arancione Cosmico esclusiva.',
  },
  {
    id: 62,
    name: 'iPhone 17 Pro Max — Lifestyle Arancione',
    price: '€1.199',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/985a98b88_IMG_1665.jpg`,
    description: 'iPhone 17 Pro Max in Arancione Cosmico nella vita reale. Il display più grande e la batteria più duratura della gamma Pro.',
  },

  // === IPHONE 17 AIR ===
  {
    id: 4,
    name: 'iPhone 17 Air — Azzurro',
    price: '€999',
    badge: 'Nuovo',
    category: 'iPhone',
    image: `${IMG}/d7f4e4986_IMG_1649.jpg`,
    description: 'Il più sottile mai realizzato. iPhone 17 Air in Azzurro unisce leggerezza estrema e potenza professionale in soli 5,6 mm di spessore.',
  },
  {
    id: 5,
    name: 'iPhone 17 Air — Bianco',
    price: '€999',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/9330a7561_IMG_1650.jpg`,
    description: 'Purezza e minimalismo nella finitura Bianca. Il nuovo iPhone 17 Air ridefinisce il concetto di smartphone sottile senza compromessi.',
  },

  // === IPHONE 17 ===
  {
    id: 6,
    name: 'iPhone 17 — Nero',
    price: '€899',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/5c59fa55f_IMG_1651.jpg`,
    description: 'Il nuovo iPhone 17 in elegante colore Nero. Display Super Retina XDR, doppia fotocamera e chip A19 per prestazioni da top di gamma.',
  },
  {
    id: 8,
    name: 'iPhone 17 — Arancione',
    price: '€899',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/6af752a1f_IMG_1653.jpg`,
    description: 'iPhone 17 nella vibrante colorazione Arancione. Design rinnovato, fotocamera avanzata e prestazioni eccezionali a un prezzo accessibile.',
  },

  // === IPHONE 16 PRO ===
  {
    id: 13,
    name: 'iPhone 16 Pro — Blu Notte',
    price: '€999',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/a86207ae7_IMG_1658.jpeg`,
    description: 'iPhone 16 Pro nella sofisticata finitura Blu Notte. Titanio di grado 5, Action Button e Fotocamera di Controllo per un\'esperienza completa.',
  },
  {
    id: 64,
    name: 'iPhone 16 Pro — Dettaglio Modulo Fotocamera',
    price: '€999',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/3e4cbc97a_IMG_1667.png`,
    description: 'Dettaglio ravvicinato della fotocamera dell\'iPhone 16 Pro. Sistema Pro con sensore da 48MP e stabilizzazione ottica per foto sempre nitide.',
  },

  // === IPHONE 16 ===
  {
    id: 10,
    name: 'iPhone 16 — Lineup Completa',
    price: '€799',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/124b7c63f_IMG_1655.jpg`,
    description: 'L\'intera gamma iPhone 16 in un\'unica immagine. Quattro modelli, quattro dimensioni, tutte le finiture per trovare quella perfetta per te.',
  },
  {
    id: 11,
    name: 'iPhone 16 — Confezione',
    price: '€799',
    badge: null,
    category: 'iPhone',
    image: `${IMG}/b76136720_IMG_1656.jpg`,
    description: 'iPhone 16 nella sua confezione originale. Include cavo USB-C, documentazione e adesivo Apple. Il nuovo controllo fotocamera rivoluziona gli scatti.',
  },

  // === APPLE WATCH ULTRA 2 ===
  {
    id: 20,
    name: 'Apple Watch Ultra 2 — Ocean Band',
    price: '€799',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: `${IMG}/37d4e3218_IMG_1673.webp`,
    description: 'Apple Watch Ultra 2 con cinturino Ocean Band. Costruito per gli avventurieri: cassa in titanio, GPS dual-band e autonomia fino a 72 ore.',
  },
  {
    id: 21,
    name: 'Apple Watch Ultra 2 — Arancione',
    price: '€799',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/41f49baf1_IMG_1674.webp`,
    description: 'Apple Watch Ultra 2 con cinturino Alpine Loop arancione. Robustezza estrema per le attività outdoor più impegnative, con display luminosissimo.',
  },

  // === APPLE WATCH SERIES 10 ===
  {
    id: 18,
    name: 'Apple Watch Series 10 — Nero',
    price: '€449',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: `${IMG}/2abb70f56_IMG_1671.jpeg`,
    description: 'Apple Watch Series 10 con cassa in alluminio Nero. Display sempre attivo più grande e sottile, sensori sanitari avanzati e nuovo ciclo di carica rapida.',
  },
  {
    id: 19,
    name: 'Apple Watch Series 10 — Cinturino Sport',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/07818d309_IMG_1672.jpeg`,
    description: 'Apple Watch Series 10 con cinturino Sport fluoroelastomerico. Leggero, resistente all\'acqua e perfetto per l\'allenamento quotidiano.',
  },
  {
    id: 23,
    name: 'Apple Watch Series 10 — Quadrante',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/ae167da00_IMG_1676.webp`,
    description: 'Il nuovo quadrante dell\'Apple Watch Series 10. Display ultra-luminoso con refresh rate adattivo e watchface completamente rinnovate.',
  },
  {
    id: 25,
    name: 'Apple Watch Series 10 — Vista Laterale',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/9567fcd33_IMG_1678.webp`,
    description: 'Profilo laterale dell\'Apple Watch Series 10. Lo spessore più sottile di sempre rende l\'orologio incredibilmente comodo al polso.',
  },
  {
    id: 24,
    name: 'Apple Watch Series 10 — Vista Macro',
    price: '€449',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: `${IMG}/20b84ec9d_IMG_1677.jpeg`,
    description: 'Dettaglio macro dell\'Apple Watch Series 10. Corona digitale ridisegnata, cristallo più sottile e sensori di salute di nuova generazione.',
  },
  {
    id: 30,
    name: 'Apple Watch Series 10 — Dettaglio Corona',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/63d33f72a_IMG_1683.webp`,
    description: 'La corona digitale ridisegnata dell\'Apple Watch Series 10. Feedback aptico preciso e nuove funzioni di interazione touch-free.',
  },
  {
    id: 34,
    name: 'Apple Watch Series 10 — Dettaglio Costruttivo',
    price: '€449',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: `${IMG}/810651f55_IMG_1688.jpeg`,
    description: 'Dettaglio costruttivo dell\'Apple Watch Series 10. Materiali premium, lavorazione di precisione e un design che unisce forma e funzione.',
  },

  // === APPLE WATCH SERIES 9 ===
  {
    id: 22,
    name: 'Apple Watch Series 9 — Cinturino Magnetico',
    price: '€399',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/afaae44e7_IMG_1675.webp`,
    description: 'Apple Watch Series 9 con cinturino magnetico. Chip S9, gesto Doppio Tocco e Siri on-device per un\'esperienza più fluida che mai.',
  },

  // === APPLE WATCH SERIES 7 ===
  {
    id: 26,
    name: 'Apple Watch Series 7 — Lineup Colori',
    price: '€349',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/5eced5370_IMG_1679.webp`,
    description: 'Apple Watch Series 7 in tutte le sue colorazioni. Display più ampio con cornici sottili e vetro frontale più resistente alle crepe.',
  },
  {
    id: 27,
    name: 'Apple Watch Series 7 — Doppio',
    price: '€349',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/4552cdca7_IMG_1680.webp`,
    description: 'Due modelli di Apple Watch Series 7 a confronto. La gamma completa per ogni stile, dall\'alluminio all\'acciaio inossidabile.',
  },

  // === APPLE WATCH SE ===
  {
    id: 29,
    name: 'Apple Watch SE — Lineup',
    price: '€249',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: `${IMG}/dabbb9a2e_IMG_1682.webp`,
    description: 'La gamma Apple Watch SE completa. Tutte le funzioni essenziali a un prezzo accessibile: perfetto per chi si avvicina al mondo Apple Watch.',
  },

  // === APPLE WATCH SERIES 4 ===
  {
    id: 28,
    name: 'Apple Watch Series 4 — Vintage',
    price: '€249',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/4fd4fd8a0_IMG_1681.webp`,
    description: 'Apple Watch Series 4, un classico senza tempo. Display più grande, ECG e rilevamento caduta: le fondamenta del moderno smartwatch.',
  },

  // === APPLE WATCH — VISTE GENERICHE ===
  {
    id: 31,
    name: 'Apple Watch — Macro Frontale',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/502c9901e_IMG_1684.jpeg`,
    description: 'Vista frontale macro dell\'Apple Watch. Il display sempre attivo mostra informazioni essenziali con un tocco di eleganza minimalista.',
  },
  {
    id: 32,
    name: 'Apple Watch — Quadrante Scuro',
    price: '€399',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/e7b796fbe_IMG_1685.jpeg`,
    description: 'Quadrante scuro dell\'Apple Watch per uno stile sofisticato. Modalità sempre attiva ottimizzata per ridurre il consumo batteria.',
  },
  {
    id: 33,
    name: 'Apple Watch — Frontale Minimal',
    price: '€399',
    badge: null,
    category: 'Apple Watch',
    image: `${IMG}/7db828c51_IMG_1687.jpeg`,
    description: 'Design frontale minimalista dell\'Apple Watch. Pulizia visiva totale con interfaccia intuitiva e focus sulle informazioni che contano.',
  },

  // === AIRPODS MAX — COLORI SOLIDI ===
  {
    id: 35,
    name: 'AirPods Max — Nero Mezzanotte',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: `${IMG}/4d51436f9_IMG_1689.jpeg`,
    description: 'AirPods Max nella colorazione Nero Mezzanotte. Cuffie over-ear premium con audio spaziale, cancellazione attiva del rumore e suono Hi-Fi.',
  },
  {
    id: 36,
    name: 'AirPods Max — Grigio Siderale',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/79fd2128e_IMG_1690.jpeg`,
    description: 'AirPods Max in Grigio Siderale. Archetto in maglia intrecciata per comfort prolungato e driver dinamico per un audio ricco e dettagliato.',
  },
  {
    id: 37,
    name: 'AirPods Max — Blu Cielo',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/dbf9ebdb0_IMG_1691.jpeg`,
    description: 'AirPods Max nella delicata finitura Blu Cielo. Audio spaziale con tracciamento dinamico della testa per un\'esperienza cinematografica immersiva.',
  },
  {
    id: 38,
    name: 'AirPods Max — Verde Alpino',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/4d118691e_IMG_1692.jpeg`,
    description: 'AirPods Max in Verde Alpino. Cancellazione del rumore leader di categoria e modalità Trasparenza per restare connessi al mondo esterno.',
  },
  {
    id: 42,
    name: 'AirPods Max — Rosa Salmone',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: `${IMG}/1c7f85735_IMG_1696.jpeg`,
    description: 'AirPods Max nella fresca finitura Rosa Salmone. Un tocco di colore per amanti del suono premium con un occhio allo stile.',
  },
  {
    id: 44,
    name: 'AirPods Max — Argento Frontale',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/17e4d98da_IMG_1698.jpeg`,
    description: 'AirPods Max in Argento, vista frontale. La classica eleganza Apple con finitura lucida e digitale corona per il controllo del volume.',
  },

  // === AIRPODS MAX — LIFESTYLE ===
  {
    id: 39,
    name: 'AirPods Max — Lifestyle Uomo',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/f35272caa_IMG_1693.jpeg`,
    description: 'AirPods Max indossate con stile. Comfort eccezionale grazie all\'archetto in maglia e cuscinetti in memory foam per sessioni di ascolto prolungate.',
  },
  {
    id: 40,
    name: 'AirPods Max — Lifestyle Donna',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: `${IMG}/0dc052de1_IMG_1694.jpeg`,
    description: 'AirPods Max in un contesto lifestyle femminile. Design elegante, materiali premium e suono d\'alta fedeltà per ogni momento della giornata.',
  },
  {
    id: 41,
    name: 'AirPods Max — Tenuti in Mano',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/21c121f53_IMG_1695.jpeg`,
    description: 'AirPods Max in primo piano. La struttura in acciaio inossidabile e gli auricolari in memory foam garantiscono durata e comfort assoluti.',
  },
  {
    id: 43,
    name: 'AirPods Max — Lifestyle Turchese',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: `${IMG}/57c940bf9_IMG_1697.jpeg`,
    description: 'AirPods Max in Turchese in uno scenario lifestyle vivace. Audio spaziale e design distintivo per chi non vuole passare inosservato.',
  },
  {
    id: 45,
    name: 'AirPods Max — Lifestyle Blu',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: `${IMG}/960bf9908_IMG_1699.jpeg`,
    description: 'AirPods Max in Blu in un contesto lifestyle. Cancellazione del rumore adattiva e audio spaziale personalizzato per un\'immersione totale.',
  },

  // === AIRPODS PRO 3 ===
  {
    id: 46,
    name: 'AirPods Pro 3 — Nuova Generazione',
    price: '€279',
    badge: 'Nuovo',
    category: 'AirPods',
    image: `${IMG}/e64ed3c7d_IMG_1700.jpeg`,
    description: 'AirPods Pro 3 di terza generazione. Cancellazione del rumore potenziata, nuovo design degli auricolari e case con ricarica USB-C.',
  },
  {
    id: 47,
    name: 'AirPods Pro 3 — Vista Macro',
    price: '€279',
    badge: 'Nuovo',
    category: 'AirPods',
    image: `${IMG}/4f2c4607d_IMG_1701.jpeg`,
    description: 'Dettaglio macro degli AirPods Pro 3. Driver ridisegnati per un suono più ricco, con audio spaziale e adattamento automatico all\'orecchio.',
  },
  {
    id: 48,
    name: 'AirPods Pro 3 — Floating',
    price: '€279',
    badge: 'Nuovo',
    category: 'AirPods',
    image: `${IMG}/99e222047_IMG_1702.png`,
    description: 'AirPods Pro 3 in vista sospesa. Design ergonomico, resistenza all\'acqua e al sudore IP54 e autonomia fino a 6 ore con una sola carica.',
  },

  // === AIRPODS PRO 2 ===
  {
    id: 50,
    name: 'AirPods Pro 2 — Floating',
    price: '€249',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/f731cdad5_IMG_1704.png`,
    description: 'AirPods Pro 2 in vista sospesa. Chip H2 per cancellazione del rumore 2x più efficace e audio spaziale personalizzato con tracciamento testa.',
  },
  {
    id: 51,
    name: 'AirPods Pro 2 — Macro',
    price: '€249',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/b2fed9641_IMG_1705.png`,
    description: 'Dettaglio macro degli AirPods Pro 2. Auricolari in silicone morbido, sensore di forza per il controllo touch e griglia acustica ridisegnata.',
  },
  {
    id: 52,
    name: 'AirPods Pro 2 — con Case',
    price: '€249',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/bf58c6cc9_IMG_1706.png`,
    description: 'AirPods Pro 2 con case di ricarica MagSafe. Lacciolo integrato, indicatore di carica e ricarica wireless per la massima praticità.',
  },

  // === AIRPODS 4 ===
  {
    id: 49,
    name: 'AirPods 4 — Lifestyle Doppio',
    price: '€149',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/6eb07533c_IMG_1703.png`,
    description: 'AirPods 4 in due varianti: standard e con cancellazione del rumore. Design semi-in-ear rivoluzionato per comfort e qualità audio superiori.',
  },

  // === AIRPODS 3 ===
  {
    id: 54,
    name: 'AirPods 3 — Lifestyle',
    price: '€169',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/2c75866bd_IMG_1708.png`,
    description: 'AirPods 3 in uno scenario lifestyle. Design leggero con sensore di forza per il controllo touch e resistenza all\'acqua IPX4.',
  },
  {
    id: 55,
    name: 'AirPods 3 — Flatlay',
    price: '€169',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/a70b6b104_IMG_1709.png`,
    description: 'AirPods 3 in vista flatlay. Case di ricarica MagSafe compatto, autonomia fino a 6 ore e audio spaziale per un\'esperienza immersiva.',
  },

  // === AIRPODS 2 ===
  {
    id: 53,
    name: 'AirPods 2 — Lifestyle Rosso',
    price: '€129',
    badge: null,
    category: 'AirPods',
    image: `${IMG}/58f298cc3_IMG_1707.png`,
    description: 'AirPods di seconda generazione in un contesto lifestyle rosso. Doppio microfono, chip H1 e "Ehi Siri" sempre attivo per un uso semplice.',
  },

  // === ECOSISTEMA APPLE ===
  {
    id: 56,
    name: 'Ecosistema Apple — Completo',
    price: '€1.499',
    badge: null,
    category: 'Ecosistema',
    image: `${IMG}/5c4627e1c_IMG_1710.png`,
    description: 'L\'intero ecosistema Apple in un\'unica soluzione. iPhone, iPad, MacBook, Apple Watch e AirPods che lavorano insieme in perfetta sinergia.',
  },
  {
    id: 57,
    name: 'Ecosistema Apple — MacBook + iPad',
    price: '€1.299',
    badge: null,
    category: 'Ecosistema',
    image: `${IMG}/5c4627e1c_IMG_1710.png`,
    description: 'Il duo perfetto per la produttività: MacBook e iPad con Sidecar, AirDrop e Universal Control per un flusso di lavoro senza interruzioni.',
  },
  {
    id: 58,
    name: 'Ecosistema Apple — Family',
    price: '€999',
    badge: null,
    category: 'Ecosistema',
    image: `${IMG}/5c4627e1c_IMG_1710.png`,
    description: 'Il pacchetto Family dell\'ecosistema Apple. Condivisione foto, calendari e abbonamenti con iCloud+ per tutta la famiglia.',
  },
  {
    id: 59,
    name: 'Ecosistema Apple — Argento',
    price: '€1.099',
    badge: null,
    category: 'Ecosistema',
    image: `${IMG}/5c4627e1c_IMG_1710.png`,
    description: 'Ecosistema Apple in elegante finitura Argento. iPhone, iPad e MacBook coordinati per uno stile coerente e una connettività senza pari.',
  },
];

export const CATEGORIES = ['Tutti', 'iPhone', 'Apple Watch', 'AirPods Max', 'AirPods', 'Ecosistema'];