// Specifiche tecniche chiave per confronto tra prodotti simili
// Chiave = id prodotto, valore = coppie etichetta/valore differenzianti

export const PRODUCT_KEY_SPECS = {
  // === IPHONE ===
  1: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Arancione Cosmico' },
  2: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Varianti multiple' },
  3: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Titanio Naturale' },
  4: { Schermo: '6,6" OLED 120Hz', Chip: 'A19', Fotocamera: 'Doppia 48MP', Colore: 'Azzurro' },
  5: { Schermo: '6,6" OLED 120Hz', Chip: 'A19', Fotocamera: 'Doppia 48MP', Colore: 'Bianco' },
  6: { Schermo: '6,1" Super Retina XDR', Chip: 'A19', Fotocamera: 'Doppia 48MP', Colore: 'Nero' },
  7: { Schermo: '6,9" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Arancione' },
  8: { Schermo: '6,1" Super Retina XDR', Chip: 'A19', Fotocamera: 'Doppia 48MP', Colore: 'Arancione' },
  9: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Frontale' },
  10: { Schermo: '6,1"–6,9" Multi', Chip: 'A18', Fotocamera: 'Variabile', Colore: 'Lineup' },
  11: { Schermo: '6,1" Super Retina XDR', Chip: 'A18', Fotocamera: 'Doppia 48MP', Colore: 'Box incluso' },
  12: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Macro 48MP', Colore: 'Dettaglio' },
  13: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A18 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Blu Notte' },
  14: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Lifestyle' },
  15: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Design' },
  16: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: '3 colori' },
  17: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Render 3D' },
  60: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Dettaglio' },
  61: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Modulo' },
  62: { Schermo: '6,9" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Arancione' },
  63: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Doppio' },
  64: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A18 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Blu Notte' },
  65: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Concept' },
  66: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Macro 48MP', Colore: 'Macro' },
  67: { Schermo: '6,3" ProMotion 120Hz', Chip: 'A19 Pro', Fotocamera: 'Tripla 48MP + 5x', Colore: 'Render 3D' },

  // === APPLE WATCH ===
  18: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Nero' },
  19: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Sport' },
  20: { Cassa: 'Titanio 49mm', Display: 'Always-On 3000nit', Autonomia: '72 ore', Colore: 'Ocean Band' },
  21: { Cassa: 'Titanio 49mm', Display: 'Always-On 3000nit', Autonomia: '72 ore', Colore: 'Arancione' },
  22: { Cassa: 'Alluminio 45mm', Display: 'Always-On LTPO2', Autonomia: '18 ore', Colore: 'Magnetico' },
  23: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Quadrante' },
  24: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Macro' },
  25: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Laterale' },
  26: { Cassa: 'Alluminio 41/45mm', Display: 'Always-On LTPO1', Autonomia: '18 ore', Colore: 'Colori' },
  27: { Cassa: 'Alluminio 41/45mm', Display: 'Always-On LTPO1', Autonomia: '18 ore', Colore: 'Doppio' },
  28: { Cassa: 'Alluminio 40/44mm', Display: 'LTPO1', Autonomia: '18 ore', Colore: 'Vintage' },
  29: { Cassa: 'Alluminio 40/44mm', Display: 'LTPO2', Autonomia: '18 ore', Colore: 'Lineup' },
  30: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Corona' },
  31: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Frontale' },
  32: { Cassa: 'Alluminio 45mm', Display: 'Always-On LTPO2', Autonomia: '18 ore', Colore: 'Scuro' },
  33: { Cassa: 'Alluminio 45mm', Display: 'Always-On LTPO2', Autonomia: '18 ore', Colore: 'Minimal' },
  34: { Cassa: 'Alluminio 42mm', Display: 'Always-On LTPO3', Autonomia: '18 ore', Colore: 'Dettaglio' },

  // === AIRPODS MAX ===
  35: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Nero Mezzanotte' },
  36: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Grigio Siderale' },
  37: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Blu Cielo' },
  38: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Verde Alpino' },
  39: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Lifestyle Uomo' },
  40: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Lifestyle Donna' },
  41: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'In Mano' },
  42: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Rosa Salmone' },
  43: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Turchese' },
  44: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Argento' },
  45: { Driver: '40mm dinamico', ANC: 'Sì adattiva', Autonomia: '20 ore', Colore: 'Blu' },

  // === AIRPODS ===
  46: { Modello: 'Pro 3', ANC: 'Sì adattiva', Autonomia: '6 ore (30h case)', Colore: 'Nuovo' },
  47: { Modello: 'Pro 3', ANC: 'Sì adattiva', Autonomia: '6 ore (30h case)', Colore: 'Macro' },
  48: { Modello: 'Pro 3', ANC: 'Sì adattiva', Autonomia: '6 ore (30h case)', Colore: 'Floating' },
  49: { Modello: 'AirPods 4', ANC: 'Opzionale', Autonomia: '5 ore (30h case)', Colore: 'Duo' },
  50: { Modello: 'Pro 2', ANC: 'Sì adattiva', Autonomia: '6 ore (30h case)', Colore: 'Floating' },
  51: { Modello: 'Pro 2', ANC: 'Sì adattiva', Autonomia: '6 ore (30h case)', Colore: 'Macro' },
  52: { Modello: 'Pro 2', ANC: 'Sì adattiva', Autonomia: '6 ore (30h case)', Colore: 'Con Case' },
  53: { Modello: 'AirPods 2', ANC: 'No', Autonomia: '5 ore (24h case)', Colore: 'Rosso' },
  54: { Modello: 'AirPods 3', ANC: 'No', Autonomia: '6 ore (30h case)', Colore: 'Lifestyle' },
  55: { Modello: 'AirPods 3', ANC: 'No', Autonomia: '6 ore (30h case)', Colore: 'Flatlay' },

  // === ECOSISTEMA ===
  56: { Dispositivi: 'iPhone+iPad+Mac+Watch', Integrazione: 'Completa', Cloud: 'iCloud+', Colore: 'Completo' },
  57: { Dispositivi: 'MacBook+iPad', Integrazione: 'Sidecar/Universal', Cloud: 'iCloud+', Colore: 'Duo' },
  58: { Dispositivi: 'Multi dispositivo', Integrazione: 'Family Sharing', Cloud: 'iCloud+ Family', Colore: 'Family' },
  59: { Dispositivi: 'iPhone+iPad+Mac', Integrazione: 'Completa', Cloud: 'iCloud+', Colore: 'Argento' },
};