// Catalogo prodotti organizzato per categoria con descrizioni in italiano

const BASE = 'https://media.base44.com/images/public/user_6a6d2ae9b2386fa15db72587';

export const PRODUCT_CATALOG = [
  // === IPHONE ===
  {
    id: 1,
    name: 'iPhone 17 Pro — Arancione Cosmico',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/cef4a37ed_generated_image.png',
    description: 'Lo smartphone più avanzato di sempre con finitura Arancione Cosmico. Chip A19 Pro, sistema fotocamera Pro con teleobiettivo 5x e display ProMotion da 6,3".',
  },
  {
    id: 2,
    name: 'iPhone 17 Pro — Variante Colori',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/e12197b0d_generated_image.png',
    description: 'Scopri tutte le finiture disponibili per iPhone 17 Pro. Struttura in titanio di grado aerospaziale e vetro Ceramic Shield di ultima generazione.',
  },
  {
    id: 3,
    name: 'iPhone 17 Pro — Titanio Naturale',
    price: '€1.099',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/ee73fc09e_generated_image.png',
    description: 'Eleganza essenziale in Titanio Naturale. Design ultra-sottile, prestazioni eccezionali e autonomia che dura tutto il giorno.',
  },
  {
    id: 4,
    name: 'iPhone 17 Air — Azzurro',
    price: '€999',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/e5dc60d8b_generated_image.png',
    description: 'Il più sottile mai realizzato. iPhone 17 Air in Azzurro unisce leggerezza estrema e potenza professionale in soli 5,6 mm di spessore.',
  },
  {
    id: 5,
    name: 'iPhone 17 Air — Bianco',
    price: '€999',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/763351eac_generated_image.png',
    description: 'Purezza e minimalismo nella finitura Bianca. Il nuovo iPhone 17 Air ridefinisce il concetto di smartphone sottile senza compromessi.',
  },
  {
    id: 6,
    name: 'iPhone 17 — Nero',
    price: '€899',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/f451f557e_generated_image.png',
    description: 'Il nuovo iPhone 17 in elegante colore Nero. Display Super Retina XDR, doppia fotocamera e chip A19 per prestazioni da top di gamma.',
  },
  {
    id: 7,
    name: 'iPhone 17 Pro Max — Arancione',
    price: '€1.199',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/8b9eead1b_generated_image.png',
    description: 'Il modello Pro Max con il più grande display ever, batteria a lunga autonomia e fotocamera professionale. Finitura Arancione Cosmico esclusiva.',
  },
  {
    id: 8,
    name: 'iPhone 17 — Arancione',
    price: '€899',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/d743ae409_generated_image.png',
    description: 'iPhone 17 nella vibrante colorazione Arancione. Design rinnovato, fotocamera avanzata e prestazioni eccezionali a un prezzo accessibile.',
  },
  {
    id: 9,
    name: 'iPhone 17 Pro — Vista Frontale',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/96cc8fa2a_generated_image.png',
    description: 'Lo splendido display ProMotion da 120Hz dell\'iPhone 17 Pro. Luminosità fino a 2000 nit all\'aperto e True Tone per colori sempre perfetti.',
  },
  {
    id: 10,
    name: 'iPhone 16 — Lineup Completa',
    price: '€799',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/d3da008bd_generated_image.png',
    description: 'L\'intera gamma iPhone 16 in un\'unica immagine. Quattro modelli, quattro dimensioni, tutte le finiture per trovare quella perfetta per te.',
  },
  {
    id: 11,
    name: 'iPhone 16 — Confezione',
    price: '€799',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/caa5547ab_generated_image.png',
    description: 'iPhone 16 nella sua confezione originale. Include cavo USB-C, documentazione e adesivo Apple. Il nuovo controllo fotocamera rivoluziona gli scatti.',
  },
  {
    id: 12,
    name: 'iPhone 17 Pro — Macro Fotocamera',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/d4434dbbf_generated_image.png',
    description: 'Il sistema fotocamera Pro dell\'iPhone 17 Pro in dettaglio. Teleobiettivo 5x, grandangolo e ultra-grandangolo per foto da vero professionista.',
  },
  {
    id: 13,
    name: 'iPhone 16 Pro — Blu Notte',
    price: '€999',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/4af6f9c37_generated_image.png',
    description: 'iPhone 16 Pro nella sofisticata finitura Blu Notte. Titanio di grado 5, Action Button e Fotocamera di Controllo per un\'esperienza completa.',
  },
  {
    id: 14,
    name: 'iPhone 17 Pro — Lifestyle',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/5ae17ef02_generated_image.png',
    description: 'iPhone 17 Pro nella vita di tutti i giorni. Prestazioni eccezionali per lavoro, creatività e intrattenimento senza limiti.',
  },
  {
    id: 15,
    name: 'iPhone 17 Pro — Dettagli Design',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/2609a0409_generated_image.png',
    description: 'I dettagli artigianali dell\'iPhone 17 Pro. Cornici ultra-sottili, pulsanti precisione e struttura in titanio per un feel premium assoluto.',
  },
  {
    id: 16,
    name: 'iPhone 17 Pro — Palette Colori',
    price: '€1.099',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/e12197b0d_generated_image.png',
    description: 'Tre finiture esclusive per iPhone 17 Pro: Titanio Naturale, Titanio Scuro e Arancione Cosmico. Scegli lo stile che ti rappresenta.',
  },
  {
    id: 17,
    name: 'iPhone 17 — Render 3D',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/adb6d123d_generated_image.png',
    description: 'Rendering 3D dell\'iPhone 17 che mostra ogni dettaglio del design. Linee pulite, materiali premium e ingegneria di precisione.',
  },
  {
    id: 60,
    name: 'iPhone 17 Pro — Dettaglio Fotocamera',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/d4434dbbf_generated_image.png',
    description: 'Primo piano sul modulo fotocamera dell\'iPhone 17 Pro. Lenti smerigliate, sensore LiDAR e flash True Tone per risultati sorprendenti.',
  },
  {
    id: 61,
    name: 'iPhone 17 Pro — Sistema Tripla Fotocamera',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/f4a75677a_generated_image.png',
    description: 'Il sistema tripla fotocamera Pro: grandangolo, ultra-grandangolo e teleobiettivo 5x. Foto notturne, ritratti e macro di qualità professionale.',
  },
  {
    id: 62,
    name: 'iPhone 17 Pro Max — Lifestyle Arancione',
    price: '€1.199',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/8b9eead1b_generated_image.png',
    description: 'iPhone 17 Pro Max in Arancione Cosmico nella vita reale. Il display più grande e la batteria più duratura della gamma Pro.',
  },
  {
    id: 63,
    name: 'iPhone 17 Pro — Doppia Variante Arancione',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/cef4a37ed_generated_image.png',
    description: 'Due esemplari di iPhone 17 Pro in Arancione Cosmico. Confronta il design anteriore e posteriore in un\'unica immagine d\'impatto.',
  },
  {
    id: 64,
    name: 'iPhone 16 Pro — Dettaglio Modulo Fotocamera',
    price: '€999',
    badge: null,
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/4af6f9c37_generated_image.png',
    description: 'Dettaglio ravvicinato della fotocamera dell\'iPhone 16 Pro. Sistema Pro con sensore da 48MP e stabilizzazione ottica per foto sempre nitide.',
  },
  {
    id: 65,
    name: 'iPhone 17 Pro — Concept Arancione',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/cef4a37ed_generated_image.png',
    description: 'Concept design dell\'iPhone 17 Pro in Arancione Cosmico. Una visione futuristica che anticipa il design della prossima generazione.',
  },
  {
    id: 66,
    name: 'iPhone 17 Pro — Macro Obiettivo',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/d4434dbbf_generated_image.png',
    description: 'Macro estrema dell\'obiettivo fotocamera dell\'iPhone 17 Pro. Precisione millimetrica e qualità ottica superiore per catturare ogni dettaglio.',
  },
  {
    id: 67,
    name: 'iPhone 17 Pro — Render 3D Arancione',
    price: '€1.099',
    badge: 'Nuovo',
    category: 'iPhone',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/adb6d123d_generated_image.png',
    description: 'Render tridimensionale dell\'iPhone 17 Pro in Arancione Cosmico. Visualizza ogni angolazione del design più innovativo di Apple.',
  },

  // === APPLE WATCH ===
  {
    id: 18,
    name: 'Apple Watch Series 10 — Nero',
    price: '€449',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/6e65c0c7f_generated_image.png',
    description: 'Apple Watch Series 10 con cassa in alluminio Nero. Display sempre attivo più grande e sottile, sensori sanitari avanzati e nuovo ciclo di carica rapida.',
  },
  {
    id: 19,
    name: 'Apple Watch Series 10 — Cinturino Sport',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/1be5cf482_generated_image.png',
    description: 'Apple Watch Series 10 con cinturino Sport fluoroelastomerico. Leggero, resistente all\'acqua e perfetto per l\'allenamento quotidiano.',
  },
  {
    id: 20,
    name: 'Apple Watch Ultra 2 — Ocean Band',
    price: '€799',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/a097da49a_generated_image.png',
    description: 'Apple Watch Ultra 2 con cinturino Ocean Band. Costruito per gli avventurieri: cassa in titanio, GPS dual-band e autonomia fino a 72 ore.',
  },
  {
    id: 21,
    name: 'Apple Watch Ultra 2 — Arancione',
    price: '€799',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/26a516880_generated_image.png',
    description: 'Apple Watch Ultra 2 con cinturino Alpine Loop arancione. Robustezza estrema per le attività outdoor più impegnative, con display luminosissimo.',
  },
  {
    id: 22,
    name: 'Apple Watch Series 9 — Cinturino Magnetico',
    price: '€399',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/91d7775ef_generated_image.png',
    description: 'Apple Watch Series 9 con cinturino magnetico. Chip S9, gesto Doppio Tocco e Siri on-device per un\'esperienza più fluida che mai.',
  },
  {
    id: 23,
    name: 'Apple Watch Series 10 — Quadrante',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/73eb14eaf_generated_image.png',
    description: 'Il nuovo quadrante dell\'Apple Watch Series 10. Display ultra-luminoso con refresh rate adattivo e watchface completamente rinnovate.',
  },
  {
    id: 24,
    name: 'Apple Watch Series 10 — Vista Macro',
    price: '€449',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/73eb14eaf_generated_image.png',
    description: 'Dettaglio macro dell\'Apple Watch Series 10. Corona digitale ridisegnata, cristallo più sottile e sensori di salute di nuova generazione.',
  },
  {
    id: 25,
    name: 'Apple Watch Series 10 — Vista Laterale',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/cb06d4621_generated_image.png',
    description: 'Profilo laterale dell\'Apple Watch Series 10. Lo spessore più sottile di sempre rende l\'orologio incredibilmente comodo al polso.',
  },
  {
    id: 26,
    name: 'Apple Watch Series 7 — Lineup Colori',
    price: '€349',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/603bb1a06_generated_image.png',
    description: 'Apple Watch Series 7 in tutte le sue colorazioni. Display più ampio con cornici sottili e vetro frontale più resistente alle crepe.',
  },
  {
    id: 27,
    name: 'Apple Watch Series 7 — Doppio',
    price: '€349',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/603bb1a06_generated_image.png',
    description: 'Due modelli di Apple Watch Series 7 a confronto. La gamma completa per ogni stile, dall\'alluminio all\'acciaio inossidabile.',
  },
  {
    id: 28,
    name: 'Apple Watch Series 4 — Vintage',
    price: '€249',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/5b50b8017_generated_image.png',
    description: 'Apple Watch Series 4, un classico senza tempo. Display più grande, ECG e rilevamento caduta: le fondamenta del moderno smartwatch.',
  },
  {
    id: 29,
    name: 'Apple Watch SE — Lineup',
    price: '€249',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/1f717dfa4_generated_image.png',
    description: 'La gamma Apple Watch SE completa. Tutte le funzioni essenziali a un prezzo accessibile: perfetto per chi si avvicina al mondo Apple Watch.',
  },
  {
    id: 30,
    name: 'Apple Watch Series 10 — Dettaglio Corona',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/eb180f4f4_generated_image.png',
    description: 'La corona digitale ridisegnata dell\'Apple Watch Series 10. Feedback aptico preciso e nuove funzioni di interazione touch-free.',
  },
  {
    id: 31,
    name: 'Apple Watch — Macro Frontale',
    price: '€449',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/6e65c0c7f_generated_image.png',
    description: 'Vista frontale macro dell\'Apple Watch. Il display sempre attivo mostra informazioni essenziali con un tocco di eleganza minimalista.',
  },
  {
    id: 32,
    name: 'Apple Watch — Quadrante Scuro',
    price: '€399',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/73eb14eaf_generated_image.png',
    description: 'Quadrante scuro dell\'Apple Watch per uno stile sofisticato. Modalità sempre attiva ottimizzata per ridurre il consumo batteria.',
  },
  {
    id: 33,
    name: 'Apple Watch — Frontale Minimal',
    price: '€399',
    badge: null,
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/6e65c0c7f_generated_image.png',
    description: 'Design frontale minimalista dell\'Apple Watch. Pulizia visiva totale con interfaccia intuitiva e focus sulle informazioni che contano.',
  },
  {
    id: 34,
    name: 'Apple Watch Series 10 — Dettaglio Costruttivo',
    price: '€449',
    badge: 'Nuovo',
    category: 'Apple Watch',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/c962b72ab_generated_image.png',
    description: 'Dettaglio costruttivo dell\'Apple Watch Series 10. Materiali premium, lavorazione di precisione e un design che unisce forma e funzione.',
  },

  // === AIRPODS MAX ===
  {
    id: 35,
    name: 'AirPods Max — Nero Mezzanotte',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/becda9f88_generated_image.png',
    description: 'AirPods Max nella colorazione Nero Mezzanotte. Cuffie over-ear premium con audio spaziale, cancellazione attiva del rumore e suono Hi-Fi.',
  },
  {
    id: 36,
    name: 'AirPods Max — Grigio Siderale',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/68c29bf33_generated_image.png',
    description: 'AirPods Max in Grigio Siderale. Archetto in maglia intrecciata per comfort prolungato e driver dinamico per un audio ricco e dettagliato.',
  },
  {
    id: 37,
    name: 'AirPods Max — Blu Cielo',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/3acddcedd_generated_image.png',
    description: 'AirPods Max nella delicata finitura Blu Cielo. Audio spaziale con tracciamento dinamico della testa per un\'esperienza cinematografica immersiva.',
  },
  {
    id: 38,
    name: 'AirPods Max — Verde Alpino',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/0f0bfa602_generated_image.png',
    description: 'AirPods Max in Verde Alpino. Cancellazione del rumore leader di categoria e modalità Trasparenza per restare connessi al mondo esterno.',
  },
  {
    id: 39,
    name: 'AirPods Max — Lifestyle Uomo',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/18489cabb_generated_image.png',
    description: 'AirPods Max indossate con stile. Comfort eccezionale grazie all\'archetto in maglia e cuscinetti in memory foam per sessioni di ascolto prolungate.',
  },
  {
    id: 40,
    name: 'AirPods Max — Lifestyle Donna',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/4f211505c_generated_image.png',
    description: 'AirPods Max in un contesto lifestyle femminile. Design elegante, materiali premium e suono d\'alta fedeltà per ogni momento della giornata.',
  },
  {
    id: 41,
    name: 'AirPods Max — Tenuti in Mano',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/becda9f88_generated_image.png',
    description: 'AirPods Max in primo piano. La struttura in acciaio inossidabile e gli auricolari in memory foam garantiscono durata e comfort assoluti.',
  },
  {
    id: 42,
    name: 'AirPods Max — Rosa Salmone',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/b7ec9d39a_generated_image.png',
    description: 'AirPods Max nella fresca finitura Rosa Salmone. Un tocco di colore per amanti del suono premium con un occhio allo stile.',
  },
  {
    id: 43,
    name: 'AirPods Max — Lifestyle Turchese',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/8ca6add33_generated_image.png',
    description: 'AirPods Max in Turchese in uno scenario lifestyle vivace. Audio spaziale e design distintivo per chi non vuole passare inosservato.',
  },
  {
    id: 44,
    name: 'AirPods Max — Argento Frontale',
    price: '€549',
    badge: null,
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/ecd24f81d_generated_image.png',
    description: 'AirPods Max in Argento, vista frontale. La classica eleganza Apple con finitura lucida e digitale corona per il controllo del volume.',
  },
  {
    id: 45,
    name: 'AirPods Max — Lifestyle Blu',
    price: '€549',
    badge: 'Nuovo',
    category: 'AirPods Max',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/ba7a544b4_generated_image.png',
    description: 'AirPods Max in Blu in un contesto lifestyle. Cancellazione del rumore adattiva e audio spaziale personalizzato per un\'immersione totale.',
  },

  // === AIRPODS ===
  {
    id: 46,
    name: 'AirPods Pro 3 — Nuova Generazione',
    price: '€279',
    badge: 'Nuovo',
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/8ca959c27_generated_image.png',
    description: 'AirPods Pro 3 di terza generazione. Cancellazione del rumore potenziata, nuovo design degli auricolari e case con ricarica USB-C.',
  },
  {
    id: 47,
    name: 'AirPods Pro 3 — Vista Macro',
    price: '€279',
    badge: 'Nuovo',
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/8ca959c27_generated_image.png',
    description: 'Dettaglio macro degli AirPods Pro 3. Driver ridisegnati per un suono più ricco, con audio spaziale e adattamento automatico all\'orecchio.',
  },
  {
    id: 48,
    name: 'AirPods Pro 3 — Floating',
    price: '€279',
    badge: 'Nuovo',
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/17db7f969_generated_image.png',
    description: 'AirPods Pro 3 in vista sospesa. Design ergonomico, resistenza all\'acqua e al sudore IP54 e autonomia fino a 6 ore con una sola carica.',
  },
  {
    id: 49,
    name: 'AirPods 4 — Lifestyle Doppio',
    price: '€149',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/e6f82887d_generated_image.png',
    description: 'AirPods 4 in due varianti: standard e con cancellazione del rumore. Design semi-in-ear rivoluzionato per comfort e qualità audio superiori.',
  },
  {
    id: 50,
    name: 'AirPods Pro 2 — Floating',
    price: '€249',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/2def9d4ff_generated_image.png',
    description: 'AirPods Pro 2 in vista sospesa. Chip H2 per cancellazione del rumore 2x più efficace e audio spaziale personalizzato con tracciamento testa.',
  },
  {
    id: 51,
    name: 'AirPods Pro 2 — Macro',
    price: '€249',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/a281839aa_generated_image.png',
    description: 'Dettaglio macro degli AirPods Pro 2. Auricolari in silicone morbido, sensore di forza per il controllo touch e griglia acustica ridisegnata.',
  },
  {
    id: 52,
    name: 'AirPods Pro 2 — con Case',
    price: '€249',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/5cbf35af4_generated_image.png',
    description: 'AirPods Pro 2 con case di ricarica MagSafe. Lacciolo integrato, indicatore di carica e ricarica wireless per la massima praticità.',
  },
  {
    id: 53,
    name: 'AirPods 2 — Lifestyle Rosso',
    price: '€129',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/f55af5747_generated_image.png',
    description: 'AirPods di seconda generazione in un contesto lifestyle rosso. Doppio microfono, chip H1 e "Ehi Siri" sempre attivo per un uso semplice.',
  },
  {
    id: 54,
    name: 'AirPods 3 — Lifestyle',
    price: '€169',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/ddfc30c0f_generated_image.png',
    description: 'AirPods 3 in uno scenario lifestyle. Design leggero con sensore di forza per il controllo touch e resistenza all\'acqua IPX4.',
  },
  {
    id: 55,
    name: 'AirPods 3 — Flatlay',
    price: '€169',
    badge: null,
    category: 'AirPods',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/46f36b217_generated_image.png',
    description: 'AirPods 3 in vista flatlay. Case di ricarica MagSafe compatto, autonomia fino a 6 ore e audio spaziale per un\'esperienza immersiva.',
  },

  // === ECOSISTEMA ===
  {
    id: 56,
    name: 'Ecosistema Apple — Completo',
    price: '€1.499',
    badge: null,
    category: 'Ecosistema',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/68d30e668_generated_image.png',
    description: 'L\'intero ecosistema Apple in un\'unica soluzione. iPhone, iPad, MacBook, Apple Watch e AirPods che lavorano insieme in perfetta sinergia.',
  },
  {
    id: 57,
    name: 'Ecosistema Apple — MacBook + iPad',
    price: '€1.299',
    badge: null,
    category: 'Ecosistema',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/1aaf257f1_generated_image.png',
    description: 'Il duo perfetto per la produttività: MacBook e iPad con Sidecar, AirDrop e Universal Control per un flusso di lavoro senza interruzioni.',
  },
  {
    id: 58,
    name: 'Ecosistema Apple — Family',
    price: '€999',
    badge: null,
    category: 'Ecosistema',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/b17099aff_generated_image.png',
    description: 'Il pacchetto Family dell\'ecosistema Apple. Condivisione foto, calendari e abbonamenti con iCloud+ per tutta la famiglia.',
  },
  {
    id: 59,
    name: 'Ecosistema Apple — Argento',
    price: '€1.099',
    badge: null,
    category: 'Ecosistema',
    image: 'https://media.base44.com/images/public/6a6d2bc9b1aeaa69d847a02b/85a788729_generated_image.png',
    description: 'Ecosistema Apple in elegante finitura Argento. iPhone, iPad e MacBook coordinati per uno stile coerente e una connettività senza pari.',
  },
];

export const CATEGORIES = ['Tutti', 'iPhone', 'Apple Watch', 'AirPods Max', 'AirPods', 'Ecosistema'];