/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * Local stub used for type-checking/build before a Convex deployment is linked.
 * Regenerated by `npx convex dev` / `npx convex codegen` — do not edit by hand.
 */
import type { QueryBuilder, MutationBuilder, ActionBuilder, HttpActionBuilder } from "convex/server";
declare const query: QueryBuilder<any, "public">;
declare const internalQuery: QueryBuilder<any, "internal">;
declare const mutation: MutationBuilder<any, "public">;
declare const internalMutation: MutationBuilder<any, "internal">;
declare const action: ActionBuilder<any, "public">;
declare const internalAction: ActionBuilder<any, "internal">;
declare const httpAction: HttpActionBuilder;
declare const queryGeneric: QueryBuilder<any, "public">;
declare const mutationGeneric: MutationBuilder<any, "public">;
declare const actionGeneric: ActionBuilder<any, "public">;
declare const httpActionGeneric: HttpActionBuilder;
declare const internalQueryGeneric: QueryBuilder<any, "internal">;
declare const internalMutationGeneric: MutationBuilder<any, "internal">;
declare const internalActionGeneric: ActionBuilder<any, "internal">;
export { query, internalQuery, mutation, internalMutation, action, internalAction, httpAction, queryGeneric, mutationGeneric, actionGeneric, httpActionGeneric, internalQueryGeneric, internalMutationGeneric, internalActionGeneric };
